menus:
	- 
		name: 首页
		link: /
	- 
		name: 分类
		link: categories/
	- 
		name: 开源项目
		link: open-source/
	- 
		name: 留言板
		link: message/

# Profile
profile:
	location: ChengDu, China
	github: yumemor
	#stackoverflow: 
		#title: yumemor
		#href: http://stackoverflow.com/users/5662132/yumemor
	#organization: 组织/公司

#Github
github: 
	username: yumemor
  popular_repos: [ysale-sms,scude-answer,cordova-plugin-alipay]

#Comments
duoshuo_username: yumemor # 多说配置
#disqus_username: yumemor # disqus 配置

# Search 
# google | local
search:
    use: local